apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: taskhub
spec:
  type: NodePort
  selector:
    app: taskhub
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
