apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: taskhub
spec:
  type: ClusterIP
  selector:
    app: taskhub
    component: database
  ports:
    - port: 5432
      targetPort: 5432
