apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: taskhub-db
  namespace: taskhub
  labels:
    app: taskhub
    component: database
    environment: lab
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: taskhub
      component: database
  template:
    metadata:
      labels:
        app: taskhub
        component: database
        environment: lab
    spec:
      containers:
        - name: database
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: taskhub
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: taskhub-secret
                  key: DATABASE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskhub-secret
                  key: DATABASE_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: database-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
